name: GitHub Pages deploy
on:
  push:
    branches:
      - master
jobs:
  checkout-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.1
      with:
        node-version: 12.x
        # Set this option if you want the action to check for the latest available version that satisfies the version spec
        check-latest: true
    - run: npm ci
    - run: npm run build --if-present
    - name: Checkout
      uses: actions/checkout@master
    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@master
      env:
        EMAIL: uhock@student.kit.edu
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BUILD_DIR: ./build
